server:
  port: 8080
spring:
  application:
    name: hyper-api
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.218:3306/hyper_api?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    cachePrepStmts: true  # 开启二级缓存
  redis:
    host: 192.168.31.218
    port: 6379
    database: 0
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    lettuce:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1

logging:
  level:
    root: WARN
  level.org.springframework.web: DEBUG
  level.com.caosoft.*: DEBUG


hyper-api:
  apikey-filter-enable: true  #是否开启API KEY请求校验
  apikey-filter-track: true  #是否显示请求校验调试日志